# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QGdzJNYDLrjuG3Y-5XHIu0gCe2QM30zy
"""

import pandas as pd
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# Load dataset
df = pd.read_csv("puskesmas_intents.csv")

# Hapus baris yang ada NaN di kolom example atau response
df = df.dropna(subset=['example', 'response'])

# Data dan label
X = df['example'].astype(str)
y = df['intent']
responses = df.groupby('intent')['response'].first().to_dict()

# TF-IDF dan Model
vectorizer = TfidfVectorizer()
X_vec = vectorizer.fit_transform(X)

model = LogisticRegression()
model.fit(X_vec, y)

# Simpan model, vectorizer, dan response
with open("chatbot_model.pkl", "wb") as f:
    pickle.dump(model, f)

with open("vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

with open("responses.pkl", "wb") as f:
    pickle.dump(responses, f)

print("✅ Model, vectorizer, dan response mapping berhasil disimpan.")